// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function AddProfile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function GetAllProfiles():Promise<Array<service.Profiles>>;

export function GetAllVideos(arg1:number,arg2:number):Promise<Array<service.Video>>;

export function UpdateProfile(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
