// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDouyinProfile(arg1, arg2) {
  return window['go']['backend']['App']['AddDouyinProfile'](arg1, arg2);
}

export function AddProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['AddProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function AddVideo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['AddVideo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteDouyinProfile(arg1) {
  return window['go']['backend']['App']['DeleteDouyinProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['App']['DeleteProfile'](arg1);
}

export function GetAllDouyinProfiles() {
  return window['go']['backend']['App']['GetAllDouyinProfiles']();
}

export function GetAllProfiles() {
  return window['go']['backend']['App']['GetAllProfiles']();
}

export function GetAllVideos(arg1, arg2) {
  return window['go']['backend']['App']['GetAllVideos'](arg1, arg2);
}

export function UpdateDouyinProfile(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateDouyinProfile'](arg1, arg2, arg3);
}

export function UpdateProfile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['UpdateProfile'](arg1, arg2, arg3, arg4, arg5, arg6);
}
