// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['AddAccount'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['backend']['App']['DeleteAccount'](arg1);
}

export function GetAllAccounts() {
  return window['go']['backend']['App']['GetAllAccounts']();
}

export function UpdateAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateAccount'](arg1, arg2, arg3, arg4, arg5);
}
