// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function GetAllAccounts():Promise<Array<service.Accounts>>;

export function GetAllVideos(arg1:number,arg2:number):Promise<Array<service.Video>>;

export function UpdateAccount(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
