// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function AddDouyinProfile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function AddProfile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddVideo(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;

export function DeleteDouyinProfile(arg1:number):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function GetAllDouyinProfiles():Promise<Array<service.ProfileDouyin>>;

export function GetAllProfiles():Promise<Array<service.Profiles>>;

export function GetAllVideos(arg1:number,arg2:number):Promise<Array<service.Video>>;

export function UpdateDouyinProfile(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateProfile(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
